CHANGELOG.md, visionatrix/backend.py, visionatrix/tasks_engine.py
After this we can work on running ComfyUI processing in our process and not spawning a separate process for that.
This will much better allow us to handle errors and still be compatible with Comfy :)
=> save all tasks history and continue after restart

scripts/easy_install.py, visionatrix/backend.py, visionatrix/flows.py, visionatrix/tasks_engine.py
Each Vix instance can have different tasks installed, so you only need to request execution of those tasks that a specific instance can process
=> fix: ask only for tasks that `Vix` instance can handle

CHANGELOG.md, visionatrix/backend.py, visionatrix/database.py, visionatrix/pydantic_models.py, visionatrix/tasks_engine.py
This allows us to add to the UI a display of whether a task is locked or just frozen, as well as possible filtering of tasks by days of creation and completion.
It is also now possible to reset tasks, without the `error` being set at the `task-restart` endpoint.
=> (feat): Task times: locked_at, created_at, updated_at, finished_at

CHANGELOG.md, visionatrix/install_update/custom_nodes.py
Tried update today my setup, after yesterday starting updating Nodes for the upcoming `0.4.0` version and got:
```
From https://github.com/Visionatrix/ComfyUI_essentials
+ 94b7450...b0cfa1b main       -> origin/main  (forced update)
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured …
```
=> reset local repo state for CustomNode when "git pull" fails

visionatrix/flows.py
I found this when I was making a flow to [remove the background](https://github.com/Visionatrix/VixFlowsDocs/pull/18), there the model is included in the node itself, that is, in fact, a flow without models for installation for our case.
=> stop dividing by zero if flow has no models

openapi.json, visionatrix/pydantic_models.py
"Remove background" flow is not supporting both UI inputs, lets add ability from backend to indicate to UI to not display them
=> Flow model: `is_seed_supported` and `is_count_supported` flags

visionatrix/flows.py
when the internet is accidentally lost and at that moment the backend decides to fetch with the replication of new flows - an unhandled exception occurs.
for this case we will simply return the last list of available flows that we had - this is definitely better than the 500 error that is returned like this.
Also increased cache time for flows from 60 sec to 180 sec,- we definitely doesn't updating flows in repo each minute =)
=> catch httpx.NetworkError exception during flows info fetch

visionatrix/flows.py
It's strange, but we didn't have this, although it seems like we have Workflows with this node - apparently they just overlooked it.
Fixed
*Found when implementing new ColorfulXL workflow for Vix 1.0*
=> processing of KSamplerAdvanced.noise_seed value

scripts/easy_install.py
The ability to update all nodes will be convenient when we have a large PR that we work on for 2+ weeks, like now with ChildTasks.
This will allow me to simultaneously freeze the nodes today and start preparing for the release without switching from the PR to run the script.
=> added ability to run `easy-install` script from the PR branches

.run/module-install-flow.run.xml, CHANGELOG.md, openapi.json, scripts/ci/release_tag_repos.py, visionatrix/__main__.py, visionatrix/basic_node_list.py, visionatrix/comfyui.py, visionatrix/install_update/__init__.py, visionatrix/install_update/custom_nodes.py, visionatrix/install_update/update.py, visionatrix/models.py, visionatrix/models_map.py, visionatrix/pydantic_models.py
This PR solves a long-standing flaw when we can specify which models to download when installing a node, but these models are not displayed on the flow installation screen.
Since we do have a direct relationship between the flow of ComfyUI, since it consists of class names, and not the repository name, and our models are tied to the repository name in the case of nodes.
```python3
BASIC_NODE_LIST = {
"ComfyUI-BRIA_AI-RMBG": {
"models": [
AIResourceModel(
name="RMGB-1.4",
save_path="{root}custom_nodes/ComfyUI-BRIA_AI-RMBG/RMBG-1.4/model.pth",
url="https://huggingface.co/andrey18106/vix_models/resolve/main/RMBG-1.4/model.pth",
homepage="https://huggingface.co/briaai/RMBG-1.4",
hash="893c16c340b1ddafc93e78457a4d94190da9b7179149f8574284c83caebf5e8c",
),
],
},
}    
```    
Therefore, this PR …
=> made models for Nodes appear in the flow models list

.github/workflows/openapi-check.yml
Without it we have `OpenAPI checks / Up to date (pull_request) Successful in 5m`
With these changes: `OpenAPI checks / Up to date (pull_request) Successful in 1m`
=> fix: use pytorch for CPU for CI speedup

README.md
I checked it today on a clean instance here: https://akash.network/
These packages on a clean Ubuntu 22.04 are enough for Visionatrix to work perfectly.
It's better to mention it in the readme (it might be worth mentioning in the docs too, according to the installation manual)
=> readme: command for Linux in to install basic packages

visionatrix/__main__.py, visionatrix/db_queries.py, visionatrix/flows.py, visionatrix/install_update/flow_install_callback.py, visionatrix/install_update/update.py, visionatrix/models.py, visionatrix/options.py, visionatrix/routes/flows.py
Working on a new benchmark, I encountered a problem when installing Visionatrix on a remote server.
With a server channel of ~1Gbps, downloading some models from a HuggingFace goes at a speed of 300-400 Mbps.
This pull request should solve this problem:
* **now by default**, two models are downloaded in parallel and this value can be changed using the new environment variable `MAX_PARALLEL_DOWNLOADS`
For home use, this will not hurt either, even a small acceleration of installation will be useful.
=> feat: new `MAX_PARALLEL_DOWNLOADS` option

visionatrix/install_update/custom_nodes.py, visionatrix/options.py
Encountered this today when I tried to run remote benchmarks.
I rented a fancy instance with a top-end video card, but for some reason the connection to GitHub was just terrible, and the one-click installation of Visionatrix definitely didn't want to work.
This should improve the situation a little.
=> fix(installation): do several  "git clone" attempts

visionatrix/tasks_engine.py
Oops, we've never seen this in UI, it didn't affect the work, but when the **benchmarker** works and displays negative task progress, it looks scary.
=> fixed: ignore ComfyUI `execution_cached` event if no cached nodes

visionatrix/basic_node_list.py, visionatrix/install_update/install.py, visionatrix/install_update/update.py
Size of `sam_vit_b_01ec64.pth` is 375 MB.
It is better to download it only for those flows where it is needed(Human Face Detailer), we already have such an opportunity.
It is nice, especially for standalone releases or for fast deploying to production, and in general we need to get rid of automatic downloads of something unnecessary.
From [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack) README:
=> stopped ImpactPact node from auto-downloading models

visionatrix/install_update/install.py, visionatrix/tasks_engine.py
we always have user settings have priority over global ones.
even though we don't have some settings for the user(user for now can't define `ollama` setting from UI), the algorithm should still be correct
=> fix: worker should ask for user setting before global

visionatrix/basic_node_list.py
For some reason, the ComfyUI-Impact-Pack node itself stopped installing it, and in version 1.4.0, Human Face Detailer is now inoperative, if the Visionatrix installation was done from scratch.
Also added download of yolo models, I missed that when I added the file “skip_download_model” that the node downloads models in the `sub-node` and it depends on this flag.
=> install "ultralytics" package for ComfyUI-Impact-Pack

visionatrix/routes/tasks.py
I completely forgot about this and didn’t check it in version 1.5, but it’s good that we saw it right away as soon as UI started using this endpoint.
=> Fix: "seed" not being taken into account in new task creation endpoint

pyproject.toml, visionatrix/comfyui.py, visionatrix/tasks_engine.py
Initially, we had it like that, but then during refactorings and adding various features - it broke, and those variables that we set (for example PYTORCH_ENABLE_MPS_FALLBACK=1) - were already set after importing Pytorch and it did not take them into account.
This is fixed in this PR.
=> import pytorch later  to support PYTORCH_ENABLE_MPS_FALLBACK

visionatrix/tasks_engine.py
In PR #200 was added a new option: `Gemini model` to allow select Gemini Pro model for those who have credits on their Google account.
This PR adds support for that option from backend side, unfortunately it is missing in `1.5.0` version and always free Gemini model is used.
=> (fix): respect the Gemini Model option from the Settings

visionatrix/tasks_engine.py
In PR #200 was added two new Ollama's options: `ollama_llm_model`(we currently do not have public Flows that uses it) and `ollama_keepalive`
This PR adds support for that options from backend side, unfortunately it is missing in 1.5.0 version.
=> respect  Ollama's `keepalive` option from the Settings

visionatrix/prompt_translation.py
Same behavior as for Ollama, if the Gemini Pro model is specified in the settings, it should be used for translations as well instead of Gemini Flash.
=> (fix): translations of prompts: respect the Gemini model in the Settings

visionatrix/comfyui.py
This PR fixes warning that almost always appear and annoys:
```
/home/user/Visionatrix/venv/lib/python3.12/site-packages/albumentations/__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15).
Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
check_for_updates()
```
This will also speed up the launch of Visionatrix a little, since there is one less request to pypi.org
=> disable automatic update checks of "Albumentations" package

visionatrix/custom_openapi.py
We get a slightly more complex algorithm than OpenAPI allows, but we will try to follow it as much as possible.
Changes in this PR:
1. A typo has been fixed, we passed the node description as a default value.
2. If the node has a default value, we consider it optional (this is the logic of the OpenAPI standard)
3. If the node does not have a default value, but has the `optional` flag, we fill in the default value `None`
As far as I understand, this will allow us to follow the OpenAPI standard, and not change the logic of the `optional` flag.
=> more correct handling of "default" nodes params

visionatrix/__main__.py, visionatrix/backend.py, visionatrix/comfyui.py, visionatrix/custom_openapi.py
The main thing I need now to test one very interesting idea is to generate OpenAPI documentation for all basic endpoints + only 1 selected flow.
The option to delete all flows and leave only 1 and generate for it is clearly very hacky.
Therefore, we quickly rework the "openapi" command, immediately add a clear description to the parameters.
=> Rework: `openapi` cmd

visionatrix/custom_openapi.py
Example of OpenAPI generation before these changes:
```python
"realism_lora_strength": {
"type": "number",
"multipleOf": 0.1,
"maximum": 1.0,
"minimum": 0.0,
"title": "Realism Lora Strength",
"description": "Realism LoRa strength"
}
```
```python                  
"fast_run": {
"type": "boolean",
"title": "Fast Run",
"description": "Fast run"
}                
```
With this PR:
```python3
"realism_lora_strength": {
"type": "number",
"multipleOf": 0.1,
"maximum": 1.0,
"minimum": 0.0,
"title": "Realism Lora Strength",
"description": "Realism LoRa strength",
"default": 0
}
```
```python3
"fast_run": {
"type": "boolean",
"title": "Fast Run",
"description": "Fast run",
"default": false
}
```
Although, as for me, it is still a bit mess until we add that the "default" parameter can be omitted …
=> specify default param for float, bool, int types

visionatrix/models_map.py
Related to recent changes in `1.7` version, should fix the embedded release where we use relative paths by default
=> Windows Embedded: use 'copy' and do not modify the models paths from node in place

openapi.json, scripts/easy_install.py, visionatrix/_version.py, visionatrix/comfyui.py
So, let's start relaxed development of the next version of Visionatrix with a release in about 9 days.
Time to bump default CUDA that is installing for the new systems.
PyTorch stopped building new wheels for `12.1` here is [post](https://github.com/pytorch/pytorch/issues/138609#issuecomment-2494607809) from their repo
=> bumped cuda from `12.1` to `12.4` version

.gitignore, scripts/easy_install.py, visionatrix/comfyui.py
This PR adds:
* Support for `--extra-model-paths-config` command line argument of ComfyUI.
* Easy Install script will suggest to create a `extra_model_paths.yaml` if it is missing.
* Visionatrix additionally will check for `extra_model_paths.yaml` in the current directory and load it if it exists.
So, before version **1.7**, we created such a file by default in installations, and it was in the ComfyUI folder.
In version **1.7**, we removed this, and now users can create it themselves if they need it and fill it in as they like.
But since many people probably don’t know about such a file and such a possibility, at least asking in the easy_install script about the possibility of creating such a file with default settings for them would be good.
=> Support for "extra-model-paths-config"

.github/workflows/tests-flows-install.yml, .github/workflows/tests-flows-run.yml, visionatrix/models.py
In this pull request https://github.com/Visionatrix/Visionatrix/pull/244 , which heavily refactored the installation of flows and models, an error was found that appeared in the CI repo with docs.
I managed to repeat it locally - the error is that it is incorrectly determined whether the models from zip archives are installed.
Changes in this PR on this topic:
* Models in 'zip' archives are always downloaded, even with the flag VIX_SERVER_FULL_MODELS=0
* A basic test has been added for now (for installing all flows in server mode), so that CI in this repo does not allow defective PRs to be merged
=> Fix installing models from "zip" archives

visionatrix/models_map.py, visionatrix/options.py
Added functionality to allow specifying multiple addresses in MODELS_CATALOG_URL, with later addresses having higher priority. Models from subsequent catalogs replace duplicates from earlier ones.
=> Support multiple addresses in MODELS_CATALOG_URL

visionatrix/models_map.py, visionatrix/options.py
To prevent such a situation from happening again (as with versions before `1.7`), when we change the format of the model catalog, all old versions immediately stop working, we introduce versioning of the model catalog using exactly the same algorithm as for flows.
The algorithm is exactly the same, I link PR with docs.
=> Versioned models catalog

openapi.json, visionatrix/basic_node_list.py, visionatrix/models.py, visionatrix/models_map.py, visionatrix/orphan_models.py, visionatrix/pydantic_models.py
This PR is a continuation of this one:
https://github.com/Visionatrix/Visionatrix/pull/253
In that PR we introduced the possibility to change ComfyUI paths to models, but without changes in this PR the Visionatrix code does not see the models immediately, because it calculated the paths at startup.
Now the paths will always be calculated dynamically, this is a little more resource-consuming, but logically more correct and should not affect the speed of flow execution at all.
=> (fix): dynamic calculation of models paths

visionatrix/models_map.py
Initially, and even now, we use three parameters by which we determine whether a model belongs to a flow.
`input_value` - the value itself that is specified in the node, usually this is the name of the model or a subpath to it.
`input_name` - the name of the key in the node, from "input_value", for example: "ckpt_name", "control_net_name", "lora_name", "vae_name".
We also have "class_name" - we use it for "IPAdapterUnifiedLoader", "ControlNetLoader" and other well-known but unique nodes.
This PR adds the type of folder from which the node loads the model, that is, for example, for "Efficient Loader" we know that "ckpt_name" looks in the "checkpoints" folder, and "lora_name" looks in the "loras" folder
Since we have already added these types to the models in `models_config.json` earlier - …
=> models mapping: using "type" to determine the model matching

visionatrix/basic_node_list.py
Although this node uses a `diffusers`  library and it is generally better not to use such things in ComfyUI (IMHO), it is very and very popular and does not have complex installation requirements.
We will simply add it to make it easier to port flows, to see less **red** nodes.
=> new "ComfyUI-Easy-Use" node

visionatrix/database.py, visionatrix/db_queries.py, visionatrix/models.py
Should fix an error that could occur on some hardware (I couldn't reproduce it on mine):
`(sqlite3.OperationalError) database is locked`
when installing flows in parallel.
=> Fix SQLite: database is locked

visionatrix/basic_node_list.py
Found why we couldn't do this before:
The `comfyui-art-venture` node overwrites the `sams` value of the directory inside ComfyUI and what we specify via the standard legal method using the ]extra_model_paths.yaml] file didn't work.
This PR fixes it, until it's merged I just made the same commit to our fork:
https://github.com/sipherxyz/comfyui-art-venture/pull/69
Now in new installs `sam_vit_b_01ec64.pth`  file will be correctly placed file in the normal "external" directory.
=> store "sam_vit_b_01ec64.pth" in a correct external models dir

scripts/easy_install.py, visionatrix/basic_node_list.py, visionatrix/settings_comfyui.py
I found a good issue (https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/478) + looked into the node sources and realized that we can also store these models correctly.
My extra-path .yamlnow looks like this(this is the default one created by Visionatrix 1.9):
```yaml
vix_models:
is_default: true
base_path: ../VixModels
checkpoints: checkpoints
text_encoders: text_encoders
clip_vision: clip_vision
controlnet: controlnet
diffusion_models: diffusion_models
diffusers: diffusers
ipadapter: ipadapter
instantid: instantid
loras: |
photomaker
loras
photomaker: photomaker
sams: sams
style_models: style_models
ultralytics: ultralytics
ultralytics_bbox: ultralytics/bbox
ultralytics_segm: ultralytics/segm
upscale_models: upscale_models
vae: vae
vae_approx: vae_approx
pulid: pulid
```
=>  mapping to "ultralytics_bbox" + segm folders

.github/workflows/embedded-windows.yml, .github/workflows/tests-flows-run.yml, scripts/easy_install.py, tests/rm_background.py, visionatrix/basic_node_list.py, visionatrix/models_map.py, visionatrix/settings_comfyui.py
Reference: https://github.com/Visionatrix/VixFlowsDocs/pull/71
In short - **this is the very node we've been looking for for so long**, with support for everything we need and working as expected.
I'm so delighted with this node that I even created a [thank you note](https://github.com/lldacing/ComfyUI_BiRefNet_ll/issues/13) for it in their repository.
Update Note
------------------
Those who will update Visionatrix `1.9` to Visionatrix `1.10` need to edit `extra_model_paths.yaml`, if you have it in your Visionatrix or ComfyUI folder, and replace the line with `rmbg` with the line with `birefnet`.
=> support for "ComfyUI_BiRefNet_ll" node

visionatrix/db_queries.py, visionatrix/models.py
This doesn't always happen now, this PR fixes it, now "buffalo_l.zip" and "antelopev2" should be marked as installed when they are installed.
=> correctly mark models in "zip" archives as installed

visionatrix/comfyui_wrapper.py
I don't quite understand why they put everything that can be easily and professionally done with reverse proxies into ComfyUI, but that's their choice.
We just disable this feature completely, as it doesn't needed from our point of view.
Reference: https://github.com/comfyanonymous/ComfyUI/pull/6672
=> disable ComfyUI response compression

scripts/easy_install.py, visionatrix/comfyui_wrapper.py
1. CUDA 12.4 --> CUDA 12.6
2. ROCM 6.2  --> ROCM 6.2.4
@andrey18106 please, approve this only after you test that on your GPU nothing breaks with `CUDA 12.6`
P.S: upcoming new benchmarks will be done after this PR, a few days later.
=> use the latest version of pytorch in new installations

visionatrix/comfyui_wrapper.py
One of the users reported that ComfyUI-Manager does not filly work for our project.
This PR and PR in the [ComfyUI-Manager repository](https://github.com/ltdrdata/ComfyUI-Manager/pull/1578) - fixes this.
=> fix: restore original cmd args, after ComfyUI import

visionatrix/prompt_translation.py, visionatrix/surprise_me.py
Removed the thinking process from **ollama** responses.
Tested on deepseek-r1, with this PR there is no more JSON parsing errors.
=> fix: Translation(ollama) with thinking models

visionatrix/flows.py, visionatrix/routes/flows.py
We have an algorithm that we return the old cache if the update process of cache is in progress, so after deleting flow, UI could display that it was installed - since the backend could sometimes return the old cache value.
=> fix: do not do full reset of installed flows cache after deleting the flow

visionatrix/comfyui_wrapper.py
@andrey18106 can you test it on some SDXL or Flux/SD3.5 task, does running with `--fast` command line argument work and does it result in some speedup or not? (bundled ComfyUI needs to be updated to make it work)
*currently supported on nvidia 4xxx/5xxx series I guess*
=> updated ComfyUIs `--fast` cmd option

.github/workflows/embedded-windows.yml, .github/workflows/tests-flows-install.yml, .gitignore, openapi.json, visionatrix/__main__.py, visionatrix/backend.py, visionatrix/comfyui_wrapper.py, visionatrix/flows.py, visionatrix/install_update/custom_nodes.py, visionatrix/options.py, visionatrix/routes/tasks.py, visionatrix/tasks_engine.py
Now we have separated env vars:
* `BASE_DATA_DIR`
* `INPUT_DIR`
* `OUTPUT_DIR`
* `USER_DIR`
* `MODELS_DIR`
Command line args `--tasks_files_dir` and `--comfyui_dir` were removed, as not needed.
Each env var can be specified through the database.
Migration steps for existing setups will be described here: #332
=> path rework:  support for Docker setups

visionatrix/install_update/install_update.py
The old behavior resulted in all private flows being lost.
It is better not to touch the DB at all during re-installation.
=> fix: do not uninstall all Flows on reinstall

visionatrix/_version.py, visionatrix/alembic/versions/f11111eac1d1_flows_table.py, visionatrix/database.py, visionatrix/db_queries.py, visionatrix/flows.py, visionatrix/models.py, visionatrix/pydantic_models.py
During the recent testing of the first docker images on https://novite.ai - it was discovered that sometimes when installing several flows in parallel using the same models - the installation progress could go beyond 100%, and sometimes fail, which led to unnecessary model reloading.
The algorithm was refactored, since now we have a table with models (it did not exist before when the original algorithm was written), - it was made so that the backend calculates the flow installation progress by it, and does not store/update it in the database in parallel from several flows.
In theory, it should become simpler and better.
=> rework(internal): parallel Flows installation

visionatrix/basic_node_list.py
Reference: https://github.com/comfyanonymous/ComfyUI/issues/7038
After we switched to ComfyUI-Manager, I have put the latest versions available in ComfiUI-Registry everywhere, but I did not notice that this node has fixes in the main branch that have not been published in the last 5 months.
We will install this node from Git.
=> use `nightly` channel for ComfyUI_FizzNodes

visionatrix/flows.py
Today I was making new video flows for version **2.0** and it turned out that one file was exported with an error - without this fix it was hard to figure out which flow from the archive (`flows.zip`) was causing the loading error.
An important little thing to make flow development easier.
=> enh: print the flow filename if flow fails to load

visionatrix/backend.py, visionatrix/flows.py, visionatrix/routes/tasks.py, visionatrix/tasks_engine.py
Old variant how output files were stored:
`ComfyUI-Data/output/12_00018_.png` - Visionatrix result
`ComfyUI-Data/output/ComfyUI_00102_.png` - ComfyUI result
All was in the same folder - that is not convenient, as they were mixed.
With this PR:
`ComfyUI-Data/output/visionatrix/12_00018_.png` - Visionatrix result
`ComfyUI-Data/output/ComfyUI_00102_.png - ComfyUI result
All results of Visionatrix now stored in the `visionatrix` sub-folder.
**Migration of files is done automatically and included in this PR.**
=> move visionatrix results to Comfy's output subfolder

visionatrix/flows.py, visionatrix/routes/tasks_internal.py
From the first versions of Visionatrix we were saving input files like this:
`11_input_image`
`677_person_face`
This PR changes that now also the extension is stored:
`1035_person_face.png`
`1049_person_face.jpg`
Also, this PR probably fixes the logic(**it was broken**) when someone will want to create a task from the input of other already existing task(we do not support that in UI currently, so I tested with `curl`)
=> feat: save input files with their extension

Makefile, docker/Dockerfile
Today, when I was testing the docker image deployment, I realized that it doesn't work on [Novita.ai](https://novita.ai) - because we have `VOLUME ["/data"]` defined in our Dockerfile - which causes an error, if do not setup such volume manually(which will be strange to do).
This should be fixed with this PR, tested it with [latest-cuda](https://github.com/Visionatrix/Visionatrix/pkgs/container/visionatrix/382333739?tag=latest-cuda) images that I'd already pushed.
Also added `DOCKER_BUILDKIT=1` to greatly speed up building of docker images by using docker cache.
=> fix: deploying on Novita.a/RunPodi;optimized Dockerfile

Makefile, visionatrix/tasks_engine.py, visionatrix/webhooks.py
Nextcloud switches to HaRP from version 32, and there applications listen to a `Unix socket`, not a `host:port`.
Let's add that if there is a custom header, it contains the name of this socket file, so as not to add a new field to the task_details table (it is already huge).
=> webhooks: custom logic when "x-transport-uds" key is present in webhook's headers

visionatrix/__main__.py, visionatrix/backend.py, visionatrix/etc.py, visionatrix/install_update/install_update.py, visionatrix/options.py
Logging levels set via `LOG_LEVEL` or `--verbose` were ignored when running the server with multiple workers (`VIX_SERVER_WORKERS=2`), causing `INFO`/`DEBUG` logs to be missed.
Solution:
- Created a central `setup_logging` function for all logging configuration.
- Call `setup_logging` from `__main__.py` (for direct commands) and within the FastAPI `lifespan` (for Uvicorn workers).
This ensures consistent logging behavior and correct level application across all supported run commands, including direct `uvicorn` invocation(`LOG_LEVEL=WARNING uvicorn --port=8288 --workers=4 visionatrix:APP`).
=> (fix): incorrect logging level when run through "uvicorn"

visionatrix/comfyui_wrapper.py
This commit: comfyanonymous/ComfyUI@22ad513 - broke the Visionatrix.
A small PR to fix that, for the latest ComfyUI version.
=> fix: compatibility with the latest ComfyUI changes

visionatrix/backend.py
Initially fix was proposed here: https://github.com/Visionatrix/Visionatrix/pull/371
Hit this myself when I was using ComfyUI flow from Visionatrix that stores the filenames in the same format.
=> fix(files migration): do not copy file to destination if it exists

visionatrix/basic_node_list.py
This node has **too high start time** impact and we do not use anything from it in our flows.
_We will try step-by-step to remove all non-needed nodes and freeze the python dependencies version list to increase security level._
**Those who have WAS Node Suite installed already still will be able to use it.** 
It will be removed only for the new installations.
=> remove was-node-suite from the default nodes

visionatrix/__main__.py, visionatrix/backend.py, visionatrix/custom_openapi.py, visionatrix/database.py, visionatrix/flows.py, visionatrix/install_update/install_update.py, visionatrix/orphan_models.py
Refactor the startup/runtime flow so only a single asyncio.run() call is executed.
**FastAPI**/**Uvicorn** now run entirely inside one event loop instead of spawning nested loops.
* Removed all secondary `asyncio.run() `usages.
* Introduced a single `asyncio.run(main())` entry-point.
* Re-wired Uvicorn startup to use its awaitable API (`server = uvicorn.Server(config); await server.serve()`).
* Added async OpenAPI route replacement (`/openapi.json`) and disabled the built-in schema path to avoid conflicts.
* Fixed a rare case where the list of installed flows was sometimes empty on startup. **This also caused errors in CI.**
=> chore: refactore __main__.py to use async

README.md, docker-compose.yml
Action for it was added in this [commit](https://github.com/Visionatrix/Visionatrix/commit/5c63eecd17ca96321e892fbf5c3138ee76b4df92)
This is part related to `docker-compose.yml` and readme
=> feat: added docker images mirroring to docker.io

visionatrix/comfyui_wrapper.py
From quick look - it was changed here:
https://github.com/comfyanonymous/ComfyUI/pull/6243
Before that PR we were needed our code to prevent ComfyUI's logs appear twice in output.
But now our code just hides ComfyUI logs and they are not visible at all, so it is not a workaround anymore, but rather a bug.
Good that we can remove it 😎
=> fix(ComfyUI logs): remove unnecessary code

visionatrix/flows.py, visionatrix/options.py
In addition to #393 where we had introduced ability for integrations to exclude nodes from the default installation, we now also add the ability to exclude default flows.
*It will cost too much time to support a fully separate list of Flows for NC(at least for now), so we will just hide some flows that can not be executed by integration, that **has limited nodes set***.
=> feat(integrations): env var to exclude available flows

visionatrix/_version.py, visionatrix/backend.py, visionatrix/options.py
I tried today to make a public templates for **RunPod** and stuck with situation, where we should use `DEFAULT` mode for easy deployment, but with the enabled authentication.
In this PR we introduce a new variable to control whether authentication is enabled or disabled.
From now the `DEFAULT` or `SERVER` modes can be with authentication or not.
Also we rename `ADMIN_OVERRIDE` to `AUTH_ADMIN_OVERRIDE` for explicit showing to which part of Visionatrix it is related.
P.S: changes in the `fnmatch.filter` part of auth part described here: https://github.com/cloud-py-api/nc_py_api/pull/357 - but we do not use that part in Visionatrix currently, so it is not a critical bug.
=> feat: AUTH to be controlled by separate ENV variable (RunPOD tempalte)

visionatrix/basic_node_list.py
This node does not support versioning in Comfy registry(it has constant version `1.0.0`) and we do not use it. 
Who still needs it, can install it from the ComfyUI-Manager
=> chore: drop rgthree-comfy node from the basic nodes list

visionatrix/prompt_translation.py, visionatrix/surprise_me.py
Today I tested it in different situations, it seems to be very good and multimodal, suitable for 16GB cards.
I also checked `gemma3:27b-it-qat` - it fits easily into a 24GB card, for those who have a 24GB card for Ollama - use the bigger one version of course.
Will make a PR with flows so that it is now there by default as well.
=> feat(llm): use gemma3:12b-it-qat as default ollama model instead of qwen2.5:14b

visionatrix/basic_node_list.py
As described [here](https://github.com/Visionatrix/VixFlowsDocs/pull/109), we cannot use `ComfyUI_FizzNodes` as it has a node with `class_type="StringConcatenate"` and recently a node with the same name was added to Comfy Core and this leads to conflicts as `ComfyUI_FizzNodes` overwrites the base ComfyUI node.
Flow `AllYourLife` was removed as it will take too much time to rewrite it without `ComfyUI_FizzNodes`
Flow `PhotoStickers 2` was adopted to work without `ComfyUI_FizzNodes`
=> chore: drop ComfyUI_FizzNodes node

visionatrix/basic_node_list.py
It was used only in AllYourLife flow, so no more needed in bundle - who needs always can install it from ComfyUI-Manager
=> chore: drop comfyui-frame-interpolation node

Makefile
I'm getting `grep: invalid option -- P` error with default grep 2.6.0 on macOS. Use `sed` instead.
=> fix(makefile): use sed for version extraction

.github/workflows/embedded-windows.yml, README.md
And mention in the Readme that `VC++ redist` should be installed on Windows.
Advice on how to install `filterpy` was taken from [here](https://github.com/lldacing/ComfyUI_PuLID_Flux_ll/issues/47#issuecomment-2704902441)
=> fix(WindowsPortable): manually pre-install "filterpy" in actions

docker/Dockerfile, docker/entrypoint.py, docker/entrypoint.sh, pyproject.toml, visionatrix/comfyui_wrapper.py
In this PR, we replace the `entrypoint.sh` script in our Docker images - which previously only executed `python -m visionatrix run --ui` - with a Python script that launches additional workers if more than one CUDA device is available.
This has been tested on RunPOD with 2x3090 GPUs, and the deployed container is now able to utilize multiple GPUs.
*This behavior can be disabled by setting the `SKIP_MULTIPLE_WORKERS` environment variable, for rare cases where multi-GPU usage is not desired.*
Additionally, this PR **fixes** incorrect GPU index reporting from workers to the server. Previously, the code always reported the index as `0`, even when `CUDA_VISIBLE_DEVICES=2` was set. This was because PyTorch assigns local indices starting from `0`, regardless of the system-wide GPU index. Our old …
=> feat(docker): use all CUDA GPUs available by default

visionatrix/flows.py
we can get "aspect ratios" from the node code itself, no need to duplicate it in the Visionatrix itself
=> chore: removed duplicated code

visionatrix/flows.py, visionatrix/flows_loras.py, visionatrix/models_map.py
By default, in the latest released version, we don't have the "Text Multiline (Code Compatible)" node for new installations, but it was still used by the backend to determine which models the workflow uses, and flows created from UI with new LoRAs on the new installations fails to execute.
_I forgot to change this when we threw out the WAS Node Suite nodepack - from the default nodes and this PR fixes this, we will use our "VixMultilineText" node instead of "Text Multiline (Code Compatible)"._
=> fix(modify-flow): use "VixMultilineText" instead of "Text Multiline" which is missing by default

visionatrix/install_update/install_update.py
This is a very old typo, but as we do not use `release` versions it was not noticed - just spotted it randomly.
_p.s: a good idea is to add CI test after next release to check this algo automatically (or to ask ComfyUI to release ComfyUI as a python package)_
=> fix(update-process): fixed typo that was breaking updating between release versions
