Visionatrix/Visionatrix

- .github/workflows/docs.yml
- flows/comicu_portrait/flow.json
- flows/ghibli_portrait/flow.json
- flows/juggernaut_lighting_loras/flow.json
- flows/models_catalog.json
- flows/photo_stickers/flow.json
- flows/photomaker_1/flow.json
- flows/playground_2_5_aesthetic/flow.json
- flows/sdxl_lighting_8/flow.json
- flows/stable_cascade/flow.json
- visionatrix/flows.py
- visionatrix/models_map.py
- visionatrix/nodes.py
- visionatrix/options.py
1. Instead of specifying for each Flow which models it uses we keep all known to us models in `models_catalog.json`
2. New `MODEL_LOAD_CLASSES` data-class that holds all know to us Comfy nodes that perform loading of models.
3. Walk throw ComfyUI nodes and fill correct models paths and also fill our `flow.json` on fly with model list.
4. At first time we will modify often the list of models, but I expect in one-two month that it will be almost ready and require almost no changes.
Now we can add new ComfyUI workflows much easier and faster.
> Semi-Automatic models detection

- visionatrix/__main__.py
- visionatrix/backend.py
- visionatrix/comfyui.py
- visionatrix/flows.py
- visionatrix/install_update/custom_nodes.py
- visionatrix/install_update/install.py
- visionatrix/install_update/update.py
- visionatrix/models.py
- visionatrix/options.py
- visionatrix/tasks_engine.py
> refactored FastAPI part

- CHANGELOG.md
- README.md
- docs/ScalingInformation.rst
- pyproject.toml
- scripts/create_user.py
- visionatrix/__main__.py
- visionatrix/backend.py
- visionatrix/database.py
- visionatrix/options.py
- visionatrix/tasks_engine.py
It’s not very debugged yet (especially the mode with `Worker to Server`) with different users, but locally it works for me.
For local usage of one instance with one default embedded worker mostly all should remain the same
> feat: Multiple Users support

- README.md
- docs/TechnicalInformation.rst
- docs/index.rst
- flows/models_catalog.json
> added `control-lora` models

- CHANGELOG.md
- visionatrix/_version.py
- visionatrix/backend.py
- visionatrix/database.py
- visionatrix/tasks_engine.py
*Requires creation of the Database from scratch*
> added "execution_time" field to "task_details"

- flows/juggernaut_lighting_loras/flow.json
- visionatrix/nodes_helpers.py
Will add the same to Playground workflow in a separate PR 🥳
> added "Aspect Ratio" to juggernaut_lighting_loras workflow

- docs/Flows/Juggernaut_Lighting_LoRAs.rst
- docs/Flows/Playground_2_5_aesthetic.rst
- flows/juggernaut_lighting_loras/flow.json
- flows/playground_2_5_aesthetic/flow.json
> added "Aspect Ratio" to playground-2.5 workflow

- visionatrix/backend.py
- visionatrix/tasks_engine.py
Although the written documentation is still very far from ideal, it is better than nothing.
An attempt to transfer documentation from Sphinx to MkDoсs will be in a separate pull request a little later
> Endpoints documentation

- CHANGELOG.md
- pyproject.toml
- visionatrix/backend.py
- visionatrix/database.py
- visionatrix/options.py
- visionatrix/pydantic_models.py
- visionatrix/tasks_engine.py
- visionatrix/tasks_engine_async.py
- visionatrix/user_backends/__init__.py
- visionatrix/user_backends/nextcloud.py
- visionatrix/user_backends/vix_db.py
> added implementation of custom user_backend: Nextcloud

- Makefile
- web/utils/api.ts
This PR adds minor change to URLs resolving and front-end client building to support embedding into Nextcloud.
> Add nextcloud support

- README.md
- docs/VixWorkflows.rst
- docs/index.rst
not finished, but documentation is a process, not a goal :)
> docs: added "Vix Workflows" chapter

- pyproject.toml
- scripts/easy_install.py
- visionatrix/_version.py
- visionatrix/install_update/custom_nodes.py
- visionatrix/install_update/install.py
- visionatrix/install_update/update.py
Should solve #79
Now we always clone full repositories(need move docs to separate repo in near future to reduce size) which will help switch from dev version to "release" easy.
> fixed "update"/"install" command

- CHANGELOG.md
- visionatrix/_version.py
- visionatrix/flows.py
- visionatrix/options.py
Docs for this: https://github.com/Visionatrix/VixFlowsDocs/pull/3
> Separate FlowsVersion for each Vix release

- .github/workflows/test-install.yml
1. added action to test macOS install (Python3.10, Python3.12)
2. added action to test Linux install (Python3.10, Python3.12)
3. added action to test Windows install (Python3.10)
> CI: tests  for `python3 -m visionatrix install`

- CHANGELOG.md
- Makefile
- openapi.json
- pyproject.toml
- scripts/generate_openapi.py
- visionatrix/_version.py
Let's try to display it beautifully in the repository with Documentation
> added openapi.json

- CHANGELOG.md
- visionatrix/install_update/install.py
- visionatrix/models_map.py
This is needed for a new workflow that will be added today.
Nothing breaking change
> parsing of `PulidModelLoader` and `Lora Loader Stack (rgthree)` classes

- .github/workflows/embedded-windows.yml
- visionatrix/install_update/custom_nodes.py
https://github.com/ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO/issues/6
implemented solution:
https://github.com/cubiq/PuLID_ComfyUI/issues/1#issuecomment-2102591918
> fixed PuLID_ComfyUI installation

- visionatrix/flows.py
- visionatrix/models_map.py
Found when implementing workflows with Flux model.
> model auto-mapping for `UNETLoader` and `DualCLIPLoader`

- visionatrix/routes/flows.py
Found during releasing of an updates for current flows we have.
Old implementation just install old version of flow and by fact was doing nothing :(
> Fixed `flow_update` endpoint

- visionatrix/install_update/__init__.py
- visionatrix/install_update/custom_nodes.py
[This](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG) node is abandoned and should be replaced with https://github.com/Extraltodeus/Skimmed_CFG node.
**The author of both nodes is the same.** 
Workflows that need to be updated:
> replaced `ComfyUI-AutomaticCFG` with `Skimmed_CFG` node 

- README.md
Tired of some models disappearing or being renamed, and sometimes realizing it too late.
This will automate this process and inform us one per day - will save us a lot of time.
Reference: https://github.com/Visionatrix/VixFlowsDocs/pull/16
> Readme badge for Checking  Models Catalog CI Action

- .github/workflows/release-tags.yml
- .gitignore
- pyproject.toml
- scripts/ci/openapi_compare.py
- scripts/ci/openapi_generate.py
- scripts/ci/release_tag_repos.py
Simplify the creation of releases, let Action push tags.
I haven't checked how it works, we'll find out this weekend during release publishing.
> CI action to tag all repositories for release

- README.md
> slightly refreshed the readme.md

- pyproject.toml
- visionatrix/backend.py
Do not know should we add support for AVIF or not.
> feat: using pillow-heif to support HEIC format as input

- CHANGELOG.md
- visionatrix/_version.py
- visionatrix/comfyui.py
I had slightly checked, looks like this PR https://github.com/comfyanonymous/ComfyUI/pull/2666 does not break anything in Visionatrix, which is very surprising for me =)
> support for new ComfyUI cmd args

- CHANGELOG.md
The hardest part is behind us, we were able to update and fix all the flows broken after PR 2666 from the ComfiUI repo.
Also, the basic work on supporting inpainteng was done, although there is still a lot missing - it already works and can be used. Great!
* https://github.com/Visionatrix/Visionatrix/pull/151
* https://github.com/Visionatrix/Visionatrix/pull/148
* https://github.com/Visionatrix/Visionatrix/pull/149
> v1.1.0 - CHANGES

- visionatrix/__main__.py
- visionatrix/backend.py
- visionatrix/comfyui.py
- visionatrix/etc.py
discovered by accident after I realized that in my local devsetup I always have the Warning level, but I still see the "info" level logs
> restore LogLvl after ComfyUI import

- visionatrix/basic_node_list.py
- visionatrix/install_update/custom_nodes.py
subj. 
Although this should be done in the node requirements themselves, many node authors do not do this.
> ability to specify platform to specified node' requirement

- Makefile
Add simple makefile run command to start visionatrix with venv in default mode with UI.
> feat: add simple dev run command

- visionatrix/comfyui.py
Implemented a temporary override of the logging.Logger.addHandler method to selectively suppress handler additions originating from the ComfyUI' `setup_logger ` function. 
No more duplication of logs:
> Duplication of logs fix

- pyproject.toml
- visionatrix/models.py
**Support for Resuming Downloads in `download_model` Function**
- Implemented logic to detect existing partial downloads and resume them using HTTP Range requests.
- Adjusted progress calculations to account for already downloaded data, ensuring accurate progress reporting.
This update allows users with unstable internet connections to resume interrupted downloads of large AI models.
> Resumable Models download logic

- visionatrix/basic_node_list.py
These PRs have been merged into the main repos:
- https://github.com/cubiq/ComfyUI_InstantID/pull/223
- https://github.com/cubiq/PuLID_ComfyUI/pull/72
and now we don't need to manually override them, as everything should be fine from now on.
> Remove overriding of reqs for PuLID_ComfyUI and ComfyUI_InstantID

- visionatrix/basic_node_list.py
- visionatrix/flows.py
- visionatrix/models_map.py
> PhotomakerPlus node

- visionatrix/__main__.py
- visionatrix/flows.py
- visionatrix/install_update/update.py
- visionatrix/options.py
- visionatrix/orphan_models.py
- visionatrix/routes/flows.py
- visionatrix/tasks_engine.py
description of this is in updated docs(linked PR)
> Support multiple values in options.FLOWS_URL

- visionatrix/_version.py
- visionatrix/options.py
- visionatrix/tasks_engine.py
This is more of an option for documentation and development
Works only with GPU, and always with GPU by default (I don't see the point in complicating the code and doing it only for the GPU that is selected in ComfyUI)
> option to measure max GPU memory consumption for flow

- .github/workflows/test-install.yml
- pyproject.toml
- tests/helpers.py
- tests/rm_background_bria.py
- visionatrix/comfyui.py
We test after installing Visionatrix, the flow installation itself:
`python3 -m visionatrix --install--flow --name=xxx`
and then launch the web server in default mode, and the creating a task from this flow and results fetch.
> CI: first tests

- visionatrix/__main__.py
Let's clean up the code, I want to try rewriting the argument parsing later, so that it would be more convenient to connect different versions of ComfyUI, and it would be easier to maintain the code.
> removed `--loglevel` cmd argument deprecated in version "1.5"

- visionatrix/flows.py
I decided to make the logic a little more beautiful, so that it would be easier to rewrite the documentation on this matter in the near future.
It looks like nothing is broken, there are still 4-5 days until the next release, we'll have time to notice if something is wrong.
> (refactor): logic of parsing ComfyUI flows inputs

- visionatrix/flows.py
In Proteus flow, if you change Aspect Ratio to any other than the standard, the following warning popped up:
`10:12:52: [get_nodes_for_translate]:WARNING: Cannot find node for **aspect_ratio** input param.`
This turned out to be a bug, when the node for translations would not be found if node was not from the "VixUi*" nodes class - that is, if it is a standard ComfyUI node marked as an input node via a modified header.
Fixing this bug required a separate refactoring, which was carried out in #219 and this PR goes further with unification.
With this PR, standard ComfyUI's nodes can now have translations, if necessary, and since all nodes are now found, there is no warning.
> (fix): Not always translations were possible for non VixUI node classes

- openapi.json
- visionatrix/comfyui.py
- visionatrix/pydantic_models.py
- visionatrix/tasks_engine.py
- visionatrix/tasks_engine_async.py
- visionatrix/tasks_engine_etc.py
We need this for more advanced benchmarks, and we will also need the information obtained in benchmarks to expand the OpenAPI specifications.
> Expanding ExecutionDetails model: "disable_smart_memory" , "vram_state"

- visionatrix/install_update/install.py
PR that fixes this was already merged: https://github.com/comfyanonymous/ComfyUI/pull/5786
> removed workaround for ComfyUI

- visionatrix/flows.py
This PR resolves race conditions in the **get_installed_flows** function that caused it to sometimes return zero installed flows on the first call, even when flows were actually installed. The issue occurred when multiple threads accessed the function simultaneously, leading to inconsistent cache states.
The fix introduces a thread-safe mechanism using threading.Lock and threading.Condition. A single thread updates the cache while other threads wait for the update to complete. This ensures consistent behavior and prevents redundant updates or stale cache reads.
---
_To test that this is fixed, I'll re-run all the tests **4** times; my observations before the fix were that we were getting this race condition in CI typically 1 in 20 times._
> Fix race conditions in get_installed_flows (thread-safe cache updates)

- visionatrix/models.py
We have archive with a top-level folder (e.g., `antelopev2.zip`) and archive without a top-level folder (e.g., `buffalo_l.zip`).
This PR fixes the issue where zip archives without a top-level folder (e.g., `buffalo_l.zip`) were extracting their contents directly into the target directory instead of a properly named subfolder. 
I think this error was in older versions too, but we didn't notice it because the **Photomaker-Plus** node simply downloaded the model from the correct path and used it.
I found this error by accident today when I was testing the newly introduced parallel download of models locally.
1. **Enhanced Extraction Logic**:
- Added a check to determine whether a zip archive contains a top-level folder.
- For archives without a top-level folder:
- Created a subfolder named …
> (fix): extraction of zip archives without top-level folders 

- visionatrix/comfyui_wrapper.py
- visionatrix/tasks_engine.py
Sync PR for this one: https://github.com/comfyanonymous/ComfyUI/pull/5450
> removed "cleanup_models" function(ComfyUI changes sync)

- visionatrix/basic_node_list.py
Will be needed for new workflows that we will publish for 1.9 version
> added ComfyUI-KJNodes

- visionatrix/basic_node_list.py
Quite popular node, it' a pity that many parts of it is not native and use `diffusers` and `tansformers`  but anyway, lets try to add it.
Recently author had removed parts that are complex to install:
https://github.com/chflame163/ComfyUI_LayerStyle/commit/eacb7ed3b66744e8617bfe839a78c82ede8795bf
> added ComfyUI_LayerStyle node

- visionatrix/comfyui_wrapper.py
Reference commit to ComfyUI repo:
https://github.com/comfyanonymous/ComfyUI/commit/ac2f0523cac112a071de43217ecc741d75e74e53#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R12
> disable diffusers/transformers telemetry

- visionatrix/basic_node_list.py
- visionatrix/comfyui_wrapper.py
- visionatrix/db_queries.py
- visionatrix/models.py
In ComfyUI, the `main.py` file was changed a bit again - nothing to worry about for us, it even became more convenient.
The `ComfyUI-Impact-Pack` node no longer installs the `ComfyUI-Impact-Subpack` node itself, and we have to do it, but this is also a positive change and it's even more convenient for us to do it.
> sync with ComfyUI/ComfyUI-Impact-Pack changes

- visionatrix/basic_node_list.py
- visionatrix/models_map.py
It's time to finally add it, now all new flows are on Flux, we need `IpAdapter` for it =)
> feat: "ComfyUI_PuLID_Flux_ll" node

- web/package-lock.json
- web/package.json
Update packages (nuxt security update related to CORS https://github.com/nuxt/nuxt/releases/tag/v3.15.3).
> chore: update npm packages

- visionatrix/flows.py
Replaced asyncio locks(that I'd added during refactoring) with threading locks for caching available flows to safely support multiple threads with different event loops.
> fix: correct locking mechanism for multiple event loops

- .github/workflows/tests-flows-run.yml
- README.md
- scripts/easy_install.py
> easy install: check presence of compilers on linux

- visionatrix/llm_utils.py
- visionatrix/surprise_me.py
Still thinking models (at least quantized ones) sometimes output invalid JSON, unfortunately... but it's better than before.
> surprise_me: use slightly different prompts to generate one or multiple prompts

- visionatrix/comfyui_proxy_middleware.py
I honestly made an effort, made PRs in ComfyUI more than a month ago (since people there had the same problems when deploying ComfyUI for NGINX, Traefik, Caddy) - but so far the PR is still not merged.
Since I don't see any more point in waiting or pinging/spamming ComfyUI developers about this (my failed attempts to bring attention to this situation are here: https://github.com/comfyanonymous/ComfyUI/pull/6376) - **it's easier to just make a workaround in Visionatrix for this**.
> workaround: support ComfyUI `userdata` endpoints

- visionatrix/basic_node_list.py
Maybe this changes will fix "test_video_flow" on macOS, if it helps - approve this and merge, please.
> fix(macOS): install ComfyUI-Frame-Interpolation from the nightly channel

- openapi.json
- visionatrix/_version.py
- visionatrix/basic_node_list.py
- visionatrix/flows.py
- visionatrix/models_map.py
- visionatrix/tasks_engine.py
[Node](https://github.com/ZenAI-Vietnam/ComfyUI_InfiniteYou) for this new tech: https://github.com/bytedance/InfiniteYou
<details>
<summary>
Spoiler: IT IS AMAZING!</summary>
</details>
> feat: InfiniteYouApply node

- .gitignore
- visionatrix/__main__.py
- visionatrix/flows.py
- visionatrix/install_update/install_update.py
- visionatrix/models.py
1. Removed usage of `concurrent.futures.ThreadPoolExecutor`
2. Made file operations use `asyncio.to_thread` when they can be long.
3. A little bit of refactoring, to make code slightly more readable.
> feat: fully async models downloading

- visionatrix/backend.py
`UI_DIR=visionatrix/client LOG_LEVEL=INFO uvicorn --access-log --port=8288 --workers=2 visionatrix:APP` now correctly reads the settings from the DB.
> fix: running as "uvicorn visionatrix:APP" 

- visionatrix/surprise_me.py
1. More different words
2. Random number of `core` categories form which to pick words
> feat: added more random to "Surprise Me" feature

- .github/workflows/embedded-windows.yml
Changes taken from here: https://github.com/comfyanonymous/ComfyUI/pull/7754
Results: `925 MB` -> `901 MB` , **better by ~2.5%**
> feat: lower size of the release package

- visionatrix/basic_node_list.py
* comfyui-impact-pack
* comfyui-impact-subpack
* comfyui-inpaint-cropandstitch
> chore: updated 3 nodes versions to latest

- visionatrix/basic_node_list.py
*preparations for the new version*
> chore: update comfy, manager, nodes

- visionatrix/basic_node_list.py
- visionatrix/install_update/custom_nodes.py
Also added passing of the new flag `--exit_on_fail` for basic node installation to ComfyUI manager.
> chore: update versions of ComfyUI and Comfy-Manager

- visionatrix/comfyui_wrapper.py
This PR https://github.com/comfyanonymous/ComfyUI/pull/8176 in the ComfyUI repository broke Visionatrix, specifically the dev version.
These small changes are similar to parts of that PR - they fix it.
> fix(ComfyUI): sync latest internal changes from the ComfyUI repo

- README.md
- visionatrix/basic_node_list.py
Also added a note to the README that we now have public RunPOD template.
> chore(nodes): updated Comfy, Manager and nodes to the latest versions

- visionatrix/install_update/install_update.py
Resolves: #409
In this PR we add that not only our requirements at the end of the installation process or update of python packages are fixed by the ComfyUI-Manager, but also that ComfyUI requirements should be fixed as well.
> fix(requirements): add ComfyUI requirements to pip_auto_fix.list file

- visionatrix/basic_node_list.py
*preparations for the upcoming release*
> chore(nodes): update Comfy and Manager to latest versions

- visionatrix/flows.py
This PR significantly enhances the `disconnect_node_graph` function by introducing an intelligent "re-wiring" or "bypass" mechanism.
Previously, when an optional input to a node was not provided, the function would trigger a cascading deletion of all subsequent nodes in the chain. This made it impossible to build robust workflows with multiple optional inputs (like images or files) that feed into batching or processing nodes.
The new logic now inspects a node being removed. If that node has a single valid "surviving" input, it attempts to re-wire that input directly to the next node in the graph, preserving the workflow's integrity.
-   **Intelligent Re-wiring:** When a node (e.g., `ImageBatch`) is removed due to a missing optional input, the function now connects its valid "surviving" …
> fix(backend): rewire existing optional input param when disconnecting node form graph

- visionatrix/basic_node_list.py
v3.38 with `uv` disabled on windows
> chore: updated Comfy-Manager to the latest version

- visionatrix/comfyui_wrapper.py
- visionatrix/flows.py
- visionatrix/routes/tasks_internal.py
reference: https://github.com/comfyanonymous/ComfyUI/pull/8830
> chore(backend): adjust logic to the latest ComfyUI async changes
